$content = @'
# DJ Contract App Environment Configuration

# EmailJS Configuration (REQUIRED)
NEXT_PUBLIC_EMAILJS_SERVICE_ID=service_9z9konq
NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=template_booking_confirmation
NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=YOUR_PUBLIC_KEY_HERE

# Firebase Configuration (REQUIRED)
NEXT_PUBLIC_FIREBASE_API_KEY=YOUR_FIREBASE_API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=YOUR_FIREBASE_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID=YOUR_FIREBASE_PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=YOUR_FIREBASE_STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=YOUR_FIREBASE_MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID=YOUR_FIREBASE_APP_ID

# Stripe Configuration (REQUIRED)
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=YOUR_STRIPE_PUBLISHABLE_KEY
STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY

# Payment Method URLs (REQUIRED)
NEXT_PUBLIC_VENMO_URL=https://venmo.com/u/Bobby-Martin-64
NEXT_PUBLIC_CASHAPP_URL=https://cash.app/$BobbyMartin64
NEXT_PUBLIC_PAYPAL_URL=https://paypal.me/bmartin4659
NEXT_PUBLIC_STRIPE_URL=

# Google Maps API (OPTIONAL)
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=YOUR_GOOGLE_MAPS_API_KEY
'@

Out-File -FilePath ".env.example" -InputObject $content -Encoding utf8
Write-Host "Created .env.example file successfully" 